### ISSUE TITLE
Previous track doesn't stop

### ISSUE THREAD

**Issue by serg-beatl** [widgetfactory/wf_plyr#1]
I use wf-plyr for playing mp3 files on Joomla site. When use more than one file for one page, I see that when first track is playing, and I press Play on second track, the first track does not stop So both tracks are playing simultaneously. Is it bug or feature? Maybe there are some options for this behavior?

**Comment by ryandemmer** [comment]
It is neither a bug nor a feature, and there is no particular reason to assume pressing play on one track should stop another, as this does not happen with the standard ```<video>``` element.

**Comment by serg-beatl** [comment]
Оh I see. I tried to build audio player with Plyr. But it needs some coding because Plyr doesn't support this functionality out of the box.
